library(readxl)
library(openxlsx)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(purrr)
library(plotly)
library(stringr)
library(ComplexHeatmap)
library(ggpubr)
library(gridExtra)
library(hrbrthemes)
library(ggprism)
library(stringr)
library(MetaboAnalystR)
library(pls)
library(reshape2)
library(igraph)

library(RJSONIO)
library(pROC)

library(ggvenn)
library(ggVennDiagram)
library(RColorBrewer)
library(cutpointr)
library(survival)
library(survminer)
library(tidycmprsk)
library(ggsurvfit)
library(randomForest)
library(datasets)
library(caret)

#install.packages("Rtsne")
#library(Rtsne)
#install.packages("mdatools")
#library(mdatools)
#library(rapportools)
#install.packages("rapport")
# install.packages("remotes")
# library(remotes)
# remotes::install_github("xia-lab/MetaboAnalystR")
#if (!requireNamespace("BiocManager", quietly = TRUE))
#  install.packages("BiocManager")
#BiocManager::install("ComplexHeatmap")
#library(preprocessCore)
# library(fuzzyjoin)